name: Docker Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-alpine3.18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

      redis:
        image: redis:7.2.1-alpine3.18
        ports:
          - "6379:6379"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-cli-action@v0.8.0
      with:
        compose-file: ./docker-compose.yml
        compose-command: version

    - name: Build and Run Tests
      run: |
        docker-compose build
        docker-compose run django python manage.py test

    - name: Clean up
      run: docker-compose down
