name: Docker Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-alpine3.18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postrgres
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

      redis:
        image: redis:7.2.1-alpine3.18
        ports:
          - "6379:6379"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./compose/Dockerfile
        push: false
        tags: event_django_image:latest

    - name: Start Services and Run Tests
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose -f docker-compose.yml exec django python manage.py test

    - name: Clean up
      run: docker-compose -f docker-compose.yml down
